apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "*" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "*" ]
  - apiGroups: [ "network.harvesterhci.io" ]
    resources: [ "ippools", "virtualmachinenetworkconfigs" ]
    verbs: [ "*" ]
  - apiGroups: [ "k8s.cni.cncf.io" ]
    resources: [ "network-attachment-definitions" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "events" ]
    verbs: [ "get", "watch", "list", "update", "create" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "*" ]
  - apiGroups: [ "kubevirt.io" ]
    resources: [ "virtualmachines" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}
  labels:
  {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harvester-vm-dhcp-controller.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}